# Generated by Django 4.2.3 on 2023-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
