# Generated by Django 4.2.3 on 2023-08-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='purchase_price',
            field=models.FloatField(),
        ),
    ]
